apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-data-ai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maksym-hrytsyshyn/open-data-ai-analytics
    targetRevision: main
    path: gitops/app
  destination:
    server: https://kubernetes.default.svc
    namespace: open-data-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
